### ISSUE TITLE
Stack support

### ISSUE THREAD

**Issue by shlok** [vmchale/libarchive#1]
Has anyone been successful in getting this library to work with a recent Stack resolver?

**Comment by ony** [comment]
I had success only with old one `lts-14.8` and `librarchive-1.0.5.1`.
With `nightly-2019-11-29` it fails on `StackSetupShim` complaining about referencing modules from hidden `Cabal-3.0.0.0`. Building from sources with just Cabal doesn't expose that.

**Comment by vmchale** [comment]
This seems to be a stack bug.
