### ISSUE TITLE
Can't be built on many distros due to >= 3.4.0

### ISSUE THREAD

**Issue by hasufell** [vmchale/libarchive#7]
```
    pkgconfig-depends: libarchive (==3.4.0 || >3.4.0) && <4.0
```

Is a very tight boundary. Current ubuntu LTS 18.04 cannot build this. This limits the possibilities for user-facing apps to use this library.

**Comment by vmchale** [comment]
Hmm, maybe it would be worth using cpp somewhere?

Some of the features (like zstd among others) could be configurable I guess!

**Comment by vmchale** [comment]
Ah, so this would require the C pre-processor to run before `c2hs` - certainly doable via cabal, but a bit of a pain, unfortunately.

**Comment by hasufell** [comment]
What's the proposed course of action? Bundle libarchive?

I would like to switch from the haskell tar implementation to libarchive in ghcup, because tars `untar` is not streaming properly.
